# Generated by Django 4.2.1 on 2023-09-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantsy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
