# Generated by Django 4.2.1 on 2023-09-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantsy", "0002_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
