# Generated by Django 4.2.1 on 2023-10-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantsy", "0003_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="category",
            field=models.CharField(max_length=100),
        ),
    ]
