# Generated by Django 4.2.1 on 2023-10-05 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plantsy", "0005_alter_cart_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="expday",
            field=models.CharField(default="10", max_length=100),
        ),
        migrations.CreateModel(
            name="payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("amount", models.CharField(max_length=20)),
                ("date", models.CharField(max_length=20)),
                ("payment_status", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plantsy.register",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("contact", models.CharField(max_length=500)),
                ("pincode", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=500)),
                ("state", models.CharField(max_length=500)),
                ("area", models.CharField(max_length=500)),
                ("buildingName", models.CharField(max_length=500)),
                (
                    "landmark",
                    models.CharField(
                        blank=True, default="No value", max_length=500, null=True
                    ),
                ),
                ("addressType", models.CharField(max_length=500)),
                ("orderAddressStatus", models.CharField(max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plantsy.register",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("orderdate", models.CharField(max_length=100)),
                ("quantity", models.CharField(blank=True, max_length=500, null=True)),
                ("total_price", models.IntegerField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="images")),
                ("category", models.CharField(blank=True, max_length=500, null=True)),
                ("expday", models.CharField(default="10", max_length=100)),
                (
                    "order_status",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plantsy.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plantsy.register",
                    ),
                ),
            ],
        ),
    ]
