# Generated by Django 4.2.1 on 2023-10-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantsy", "0007_order_contactnum_order_orderaddress_order_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="userstatus",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
