# Generated by Django 4.2.1 on 2023-10-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantsy", "0008_register_userstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="expdate",
            field=models.CharField(default="10", max_length=200),
        ),
    ]
