# Generated by Django 4.2.1 on 2023-10-08 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plantsy", "0009_product_expdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="images/")),
                ("price", models.CharField(max_length=300)),
                ("favStatus", models.CharField(max_length=200)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plantsy.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plantsy.register",
                    ),
                ),
            ],
        ),
    ]
