# Generated by Django 4.2.1 on 2023-10-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantsy", "0010_alter_order_image_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating_count",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.FloatField(default=0.0, max_length=100, null=True),
        ),
    ]
